### ISSUE TITLE
Implement useAngle, angleCenter, and angle props

### ISSUE THREAD

**Issue by airandfingers** [react-native-web-community/react-native-web-linear-gradient#10]
This package takes the props `useAngle`, `angleCenter`, and `angle`, but it doesn't use them, instead calculating the angle in [`getAngle`](https://github.com/react-native-web-community/react-native-web-linear-gradient/blob/master/src/index.js#L29) based on `start`, `end`, `width`, and `height`.

From the [react-native-linear-gradient docs](https://github.com/react-native-community/react-native-linear-gradient#useangle--angle--anglecenter):

#### useAngle / angle / angleCenter
You may want to achieve an angled gradient effect, similar to those in image editors like Photoshop.  
One issue is that you have to calculate the angle based on the view's size, which only happens asynchronously and will cause unwanted flickr.

In order to do that correctly you can set `{ useAngle: true, angle: 45, angleCenter: { x: 0.5, y: 0.5} }`, to achieve a gradient with a 45 degrees angle, with its center positioned in the view's exact center.

`useAngle` is used to turn on/off angle based calculation (as opposed to `start`/`end`).  
`angle` is the angle in degrees.  
`angleCenter` is the center point of the angle (will control the weight and stretch of the gradient like it does in photoshop.

**Comment by Minishlink** [comment]
`angleCenter` prop doesn't seem to be easily reproducible in CSS, if someone has the need for it and the time to do it, please send a PR or at least reopen an issue :)
