### ISSUE TITLE
Storybook Issue: 'requireNativeComponent' is not a function

### ISSUE THREAD

**Issue by ds8k** [react-native-web-community/react-native-web-linear-gradient#13]
After adding this library to one of my components, Storybook is yelling about this line in `common.js`:

```
export default requireNativeComponent('BVLinearGradient');
...
TypeError: (0 , _reactNative.requireNativeComponent) is not a function
    at Object../node_modules/react-native-linear-gradient/common.js 
```

It looks like storybook is set up for this library, so the issue must be with my configuration. Is there anything special I need to get this to work properly?

**Comment by Minishlink** [comment]
You need to alias `react-native-linear-gradient` with `react-native-web-linear-gradient`. It's done in [the webpack config file](https://github.com/react-native-web-community/react-native-web-linear-gradient/blob/master/docs/.storybook/webpack.config.js#L25). You'd need to add `'react-native-linear-gradient': 'react-native-web-linear-gradient'`.
