### ISSUE TITLE
Stripped alpha channel on mobile safari

### ISSUE THREAD

**Issue by tyre** [react-native-web-community/react-native-web-linear-gradient#14]
Here is the element in React Native:

```
<LinearGradient
  colors={[
    "rgba(255,255,255,0)",
    "rgba(255,255,255,255)",
  ]}
  style={{height: 20}}
/>
```

In Safari, this is the CSS that's generated: 

```
background-image: linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255));
```

Since the alpha channel is stripped, there's no transparency and the gradient appears as a solid white block.

Setting the first color to `"transparent"` creates a gradient from transparent black to opaque white, which isn't good.

**Comment by tyre** [comment]
explicitly setting it on a view works, however

```
<View
  style={{
    height: 20,
    background: "linear-gradient(rgba(255,255,255,0), rgba(255,255,255,255)"
  }}
/>
```

**Comment by Minishlink** [comment]
This is happening because your CSS color is wrong, and mobile Safari ignores it: the latest argument of rgba is the opacity, and this is between 0 and 1, not 0 and 255 ;)
