### ISSUE TITLE
Feature Request: react-native-radial-gradient

### ISSUE THREAD

**Issue by DaKaZ** [react-native-web-community/react-native-web-linear-gradient#2]
Hello,

Thank you for the amazing `react-native-web-linear-gradient` as I've used it in 3 projects now!  I was wondering, with your experience in doing this module, if you'd be willing to tackle radial gradients?  We have been using https://github.com/surajitsarkar19/react-native-radial-gradient for native application but there is no translation to web.  I just don't know the internals of the css implementation well enough to try and do this myself.  Any interest in adding support for radial?

**Comment by Naturalclar** [comment]
@DaKaZ @Minishlink Hello :wave: I'd be willing to work on the web implementation of react-native-radial-gradient.
Would that be something that can be included as part of react-native-web-community?

**Comment by Minishlink** [comment]
@Naturalclar Sure, I can open a new repo for you. The best thing to do first though is to first check with the original repo's owner if they're good with a PR to add web support: it's best to have only one repo with android/ios/web rather than two seperate repos :)

**Comment by Minishlink** [comment]
@Naturalclar Contact me on my email address (on my GitHub profile) if you need a repo here
