### ISSUE TITLE
Linear gradient for both mobile and web

### ISSUE THREAD

**Issue by thodwris** [react-native-web-community/react-native-web-linear-gradient#9]
Hello,

Is it necessary to have both react-native-linear-gradient and react-native-web-linear-gradient
and choose accordingly the platform the corresponding library?

Thank you

**Comment by drgx** [comment]
you only need to install `react-native-web-linear-gradient` for web and `react-native-linear-gradient` for apps.  
And for web you need to aliasing the `react-native-linear-gradient` to `react-native-web-linear-gradient` on webpack config but you dont need to install `react-native-linear-gradient`
